import { Poppins } from 'next/font/google';
import "../../globals.css";
import Header from "../components/header";
import Footer from "../components/footer";
import { cn } from "@/app/lib/utils";
import {Providers} from '../../providers'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
    <html lang="en" className="dark">
      <body className={cn("bg-background dark:bg-background",poppins.className)}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
    </Providers>
  );
}
